# ==========================================
# 1. Estágio de Build (Base com Node 18)
# ==========================================
FROM node:24-alpine AS builder
RUN corepack enable && corepack prepare pnpm@latest --activate
WORKDIR /app

# Copia a estrutura essencial do monorepo para montagem do contexto
COPY pnpm-lock.yaml pnpm-workspace.yaml package.json turbo.json ./
COPY apps/backend ./apps/backend

# Instala as dependências e faz o build do backend
RUN pnpm install --frozen-lockfile
RUN pnpm --filter backend build

# ==========================================
# 2. Estágio de Produção / Execução
# ==========================================
FROM node:18-alpine AS runner
WORKDIR /app
ENV NODE_ENV=production

RUN corepack enable && corepack prepare pnpm@latest --activate

# Copia apenas os arquivos necessários para rodar em produção
COPY --from=builder /app/package.json ./
COPY --from=builder /app/pnpm-lock.yaml ./
COPY --from=builder /app/pnpm-workspace.yaml ./
COPY --from=builder /app/apps/backend/package.json ./apps/backend/
COPY --from=builder /app/apps/backend/dist ./apps/backend/dist

# Instala apenas as dependências de produção do monorepo
RUN pnpm install --prod --frozen-lockfile

EXPOSE 3000
CMD ["pnpm", "--filter", "backend", "prod"]